# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import products_pb2 as products__pb2


class productsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get = channel.unary_unary(
        '/products.products/get',
        request_serializer=products__pb2.GetProduct.SerializeToString,
        response_deserializer=products__pb2.Product.FromString,
        )
    self.create = channel.unary_unary(
        '/products.products/create',
        request_serializer=products__pb2.Product.SerializeToString,
        response_deserializer=products__pb2.Product.FromString,
        )


class productsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_productsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=products__pb2.GetProduct.FromString,
          response_serializer=products__pb2.Product.SerializeToString,
      ),
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=products__pb2.Product.FromString,
          response_serializer=products__pb2.Product.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'products.products', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
