FROM nameko-example-base

ADD wheelhouse /var/nameko/wheelhouse

COPY config.yaml /var/nameko/config.yaml
COPY run.sh /var/nameko/run.sh
COPY alembic.ini /var/nameko/alembic.ini
ADD alembic /var/nameko/alembic

RUN chmod +x /var/nameko/run.sh

WORKDIR /var/nameko/

RUN . /appenv/bin/activate; \
    pip install --no-index -f wheelhouse nameko_examples_orders

EXPOSE 8000

CMD . /appenv/bin/activate; \
    /var/nameko/run.sh;
